apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "v4cvmfs.fullname" . }}
data:
  default.vcl: |-
    vcl 4.1;
    import dynamic;
    import directors;

    {{- range $nindex, $be := .Values.backends }}
    backend {{ $be.name }} {
        .host = "{{ $be.host }}";
        .port = "{{ $be.port }}";
    }
    {{- end }}

    acl local {
        {{.Values.acl | nindent 4 }}
    }

    sub vcl_recv {
        if (!(client.ip ~ local)) {
            return (synth(405));
        }        
        if (req.method != "GET" && req.method != "HEAD") {
            return (pipe);
        }

        {{- range $nindex, $be := .Values.backends }}
        if (req.restarts == {{ $nindex }}) {
            set req.backend_hint = {{ $be.name }};
        }
        {{- end }}

    }

    sub vcl_backend_response {
        if (beresp.status >= 400 && req.restarts < {{ len .Values.backends }}) {
            return(restart);
        }
    }

    sub vcl_backend_error {
        if (req.restarts < {{ len .Values.backends }}) {
            return(retry);
        }
    }

    sub vcl_backend_fetch {
        unset bereq.http.host;
    }


